### ISSUE TITLE
complie issue with Eigen version

### ISSUE THREAD

**Issue by Jaemin87** [junhyeokahn/PnC#3]
In the master branch, "util.cpp"  utilizes "Eigen::CompleteOrthogonalDecomposition<Eigen::MatrixXd>" This expression of the class is valid only in Eigen 3.3.X ( I tried to complie this code in Eigen 3.2.X and Eigen 3.4.X. But  I can see compile errors related to this construction.)  please inform that users using Ubuntu 16.04 need to specify the Eigen version. Because "sudo apt-get install libeigen3-dev" provides Eigen 3.2.X in Ubuntu 16.04.

**Comment by junhyeokahn** [comment]
I just checked Eigen 3.2.X does not have ```Eigen::CompleteOrthogonalDecomposition``` but the Eigen [3.3.X](https://gitlab.com/libeigen/eigen/-/blob/3.3/Eigen/QR#L37) and [3.4.X](https://gitlab.com/libeigen/eigen/-/blob/3.4/Eigen/QR#L37) do have.

I have added the minimum Eigen version in the top-level ```CMakeLists.txt``` to enforce using the right version.

Thanks!
